$env:AZURE_RESOURCE_GROUP = 'MyTestResourceGroup'
$env:AZURE_CLIENT_ID = 'fb0fa1dc-9db0-4ad9-9c65-85ce0f9a31ab'
$env:AZURE_TENANT_ID = '72f988bf-86f1-41af-91ab-2d7cd011db47'
$env:AZURE_CLIENT_SECRET= 'EvpJWg6VuguBN0Y8bu07eo7zsvF.0AtwNk'
$env:SYNAPSE_DEV_URL= 'https://xchfeathrtest4spark.dev.azuresynapse.net'
$env:SYNAPSE_POOL_NAME= 'spark31'
$env:SYNAPSE_WORKSPACE_DIR= 'abfss://xchfeathrtest4fs@xchfeathrtest4sto.dfs.core.windows.net/'
$env:REDIS_PASSWORD= 'a6yyCcl1c57Ey3m2khYIlrThmizEFQIJKAzCaKNqx6M='
$env:REDIS_HOST= 'xchfeathrtest4redis.redis.cache.windows.net'
$env:FEATHR_RUNTIME_LOCATION= 'https://azurefeathrstorage.blob.core.windows.net/public/feathr_20220204.jar'
$env:AZURE_PURVIEW_NAME= 'xchfeathrtest4purview'
