name: Publish package to the Maven Central Repository
on:
  push:
    # This pipeline will get triggered everytime there is a new tag created.
    # It is required
    tags: ["*"]
    branches:
      - "gradlefix"

jobs:
  publish-to-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

    # Setting up JDK 8, this is required to build Feathr
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "temurin"
          server-id: ossrh
          server-username: ORG_GRADLE_PROJECT_mavenCentralUsername
          server-password: ORG_GRADLE_PROJECT_mavenCentralPassword
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ORG_GRADLE_PROJECT_signingInMemoryKeyPassword

    # Publish Released Fat Jar to Blob Storage 
      - name: Gradle build
        run: |  
          ./gradlew build
          # remote folder for CI upload
          echo "CI_SPARK_REMOTE_JAR_FOLDER=feathr_jar_release" >> $GITHUB_ENV
          # get local jar name without path
          echo "FEATHR_LOCAL_JAR_FULL_NAME_PATH=$(ls build/libs/*.jar)" >> $GITHUB_ENV
      
      - name: Azure Blob Storage Upload (Overwrite)
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{secrets.SPARK_JAR_BLOB_CONNECTION_STRING}}
          name: ${{ env.CI_SPARK_REMOTE_JAR_FOLDER}}
          path: ${{ env.FEATHR_LOCAL_JAR_FULL_NAME_PATH}}
          container: ${{secrets.SPARK_JAR_BLOB_CONTAINER}}
          cleanup: "true"